; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM14
board_build.partitions = min_spiffs.csv
data_dir = src/data
monitor_port = COM14
; Local Arduino libraries: ui (SquareLine), TFT_eSPI (with custom User_Setup.h), lv_conf.h
lib_extra_dirs = ../libraries
lib_deps =
    lvgl/lvgl@^8.4.0
    paulstoffregen/XPT2046_Touchscreen
    esp32async/ESPAsyncWebServer@^3.10.1
    dfrobot/DFRobotDFPlayerMini
    witnessmenow/UniversalTelegramBot
    bblanchon/ArduinoJson
    adafruit/Adafruit NeoPixel
    adafruit/Adafruit PWM Servo Driver Library
    adafruit/Adafruit BusIO
build_flags =
    -DLV_CONF_INCLUDE_SIMPLE
    -I../libraries
