// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_BlankSCR_screen_init(void)
{
    ui_BlankSCR = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BlankSCR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_BlankSCR, ui_event_BlankSCR, LV_EVENT_ALL, NULL);

}
