// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ClockSCR_screen_init(void)
{
    ui_ClockSCR = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ClockSCR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ClockSCR, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ClockSCR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ClockSCRLBL = lv_label_create(ui_ClockSCR);
    lv_obj_set_width(ui_ClockSCRLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ClockSCRLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ClockSCRLBL, 0);
    lv_obj_set_y(ui_ClockSCRLBL, -16);
    lv_obj_set_align(ui_ClockSCRLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ClockSCRLBL, "15:36");
    lv_obj_set_style_text_color(ui_ClockSCRLBL, lv_color_hex(0xD5E6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ClockSCRLBL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ClockSCRLBL, &ui_font_Timefont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateSCRLBL = lv_label_create(ui_ClockSCR);
    lv_obj_set_width(ui_DateSCRLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateSCRLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DateSCRLBL, 0);
    lv_obj_set_y(ui_DateSCRLBL, 30);
    lv_obj_set_align(ui_DateSCRLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DateSCRLBL, "2024-03-06");
    lv_obj_set_style_text_color(ui_DateSCRLBL, lv_color_hex(0xA4C2EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DateSCRLBL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DateSCRLBL, &ui_font_Datefont, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ClockSCR, ui_event_ClockSCR, LV_EVENT_ALL, NULL);

}
