// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_MainSCR_screen_init(void)
{
    ui_MainSCR = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainSCR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainSCR, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainSCR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingBTN = lv_btn_create(ui_MainSCR);
    lv_obj_set_width(ui_SettingBTN, 78);
    lv_obj_set_height(ui_SettingBTN, 33);
    lv_obj_set_x(ui_SettingBTN, 112);
    lv_obj_set_y(ui_SettingBTN, 97);
    lv_obj_set_align(ui_SettingBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SettingBTN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingBTN, lv_color_hex(0x3175DD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingBTN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingBTN, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingBTNLBL = lv_label_create(ui_SettingBTN);
    lv_obj_set_width(ui_SettingBTNLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingBTNLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingBTNLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingBTNLBL, "Settings");

    ui_DispenseBTN = lv_btn_create(ui_MainSCR);
    lv_obj_set_width(ui_DispenseBTN, 78);
    lv_obj_set_height(ui_DispenseBTN, 114);
    lv_obj_set_x(ui_DispenseBTN, 112);
    lv_obj_set_y(ui_DispenseBTN, -38);
    lv_obj_set_align(ui_DispenseBTN, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_DispenseBTN, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_DispenseBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DispenseBTN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DispenseBTN, lv_color_hex(0x3175DD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DispenseBTN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DispenseBTNLBL = lv_label_create(ui_DispenseBTN);
    lv_obj_set_width(ui_DispenseBTNLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DispenseBTNLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DispenseBTNLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DispenseBTNLBL, "Dispense \nSelected\nTray");
    lv_obj_set_style_text_align(ui_DispenseBTNLBL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DispenseBTNLBL, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TraycfgBTN = lv_btn_create(ui_MainSCR);
    lv_obj_set_width(ui_TraycfgBTN, 78);
    lv_obj_set_height(ui_TraycfgBTN, 49);
    lv_obj_set_x(ui_TraycfgBTN, 112);
    lv_obj_set_y(ui_TraycfgBTN, 50);
    lv_obj_set_align(ui_TraycfgBTN, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_TraycfgBTN, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_TraycfgBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TraycfgBTN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TraycfgBTN, lv_color_hex(0x3175DD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TraycfgBTN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TraycfgBTNLBL = lv_label_create(ui_TraycfgBTN);
    lv_obj_set_width(ui_TraycfgBTNLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TraycfgBTNLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TraycfgBTNLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TraycfgBTNLBL, "Tray\nConfig");
    lv_obj_set_style_text_align(ui_TraycfgBTNLBL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TraycfgBTNLBL, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ClockLBL = lv_label_create(ui_MainSCR);
    lv_obj_set_width(ui_ClockLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ClockLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ClockLBL, 100);
    lv_obj_set_y(ui_ClockLBL, -108);
    lv_obj_set_align(ui_ClockLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ClockLBL, "");

    ui_WifiIconIMG = lv_img_create(ui_MainSCR);
    lv_img_set_src(ui_WifiIconIMG, &ui_img_231307730);
    lv_obj_set_width(ui_WifiIconIMG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiIconIMG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiIconIMG, 136);
    lv_obj_set_y(ui_WifiIconIMG, -108);
    lv_obj_set_align(ui_WifiIconIMG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiIconIMG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WifiIconIMG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NoWifiIconIMG = lv_img_create(ui_MainSCR);
    lv_img_set_src(ui_NoWifiIconIMG, &ui_img_2117515183);
    lv_obj_set_width(ui_NoWifiIconIMG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NoWifiIconIMG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NoWifiIconIMG, 136);
    lv_obj_set_y(ui_NoWifiIconIMG, -108);
    lv_obj_set_align(ui_NoWifiIconIMG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NoWifiIconIMG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_NoWifiIconIMG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PAGE1CON = lv_obj_create(ui_MainSCR);
    lv_obj_remove_style_all(ui_PAGE1CON);
    lv_obj_set_width(ui_PAGE1CON, 225);
    lv_obj_set_height(ui_PAGE1CON, 240);
    lv_obj_clear_flag(ui_PAGE1CON, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BaseIMG = lv_img_create(ui_PAGE1CON);
    lv_img_set_src(ui_BaseIMG, &ui_img_base_png);
    lv_obj_set_width(ui_BaseIMG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BaseIMG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BaseIMG, 1);
    lv_obj_set_y(ui_BaseIMG, 20);
    lv_obj_set_align(ui_BaseIMG, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_BaseIMG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BaseIMG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TrayIMG1 = lv_img_create(ui_PAGE1CON);
    lv_img_set_src(ui_TrayIMG1, &ui_img_tray_png);
    lv_obj_set_width(ui_TrayIMG1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayIMG1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayIMG1, 1);
    lv_obj_set_y(ui_TrayIMG1, -57);
    lv_obj_set_align(ui_TrayIMG1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_TrayIMG1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TrayIMG1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_TrayIMG1, lv_color_hex(0x3175DD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TrayIMG1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TrayIMG1, lv_color_hex(0x3175DD), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_TrayIMG1, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_width(ui_TrayIMG1, 3, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_pad(ui_TrayIMG1, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_TrayNumLBL1 = lv_label_create(ui_TrayIMG1);
    lv_obj_set_width(ui_TrayNumLBL1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayNumLBL1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayNumLBL1, 65);
    lv_obj_set_y(ui_TrayNumLBL1, -1);
    lv_obj_set_align(ui_TrayNumLBL1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TrayNumLBL1, "#1");
    lv_obj_set_style_text_color(ui_TrayNumLBL1, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TrayNumLBL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TrayCheckIMG1 = lv_img_create(ui_TrayIMG1);
    lv_img_set_src(ui_TrayCheckIMG1, &ui_img_red_cross_png);
    lv_obj_set_width(ui_TrayCheckIMG1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayCheckIMG1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayCheckIMG1, 40);
    lv_obj_set_y(ui_TrayCheckIMG1, 0);
    lv_obj_set_align(ui_TrayCheckIMG1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TrayCheckIMG1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TrayCheckIMG1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TrayLBL1 = lv_label_create(ui_TrayIMG1);
    lv_obj_set_width(ui_TrayLBL1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayLBL1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayLBL1, 29);
    lv_obj_set_y(ui_TrayLBL1, -1);
    lv_obj_set_align(ui_TrayLBL1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TrayLBL1, "12345678901234");
    lv_obj_set_style_text_color(ui_TrayLBL1, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TrayLBL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TrayLBL1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TrayIMG2 = lv_img_create(ui_PAGE1CON);
    lv_img_set_src(ui_TrayIMG2, &ui_img_tray_png);
    lv_obj_set_width(ui_TrayIMG2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayIMG2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayIMG2, 1);
    lv_obj_set_y(ui_TrayIMG2, -89);
    lv_obj_set_align(ui_TrayIMG2, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_TrayIMG2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TrayIMG2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_TrayIMG2, lv_color_hex(0x3175DD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TrayIMG2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_TrayIMG2, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_TrayIMG2, 152, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TrayIMG2, lv_color_hex(0x3175DD), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_TrayIMG2, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_width(ui_TrayIMG2, 3, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_pad(ui_TrayIMG2, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_TrayNumLBL2 = lv_label_create(ui_TrayIMG2);
    lv_obj_set_width(ui_TrayNumLBL2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayNumLBL2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayNumLBL2, 65);
    lv_obj_set_y(ui_TrayNumLBL2, -1);
    lv_obj_set_align(ui_TrayNumLBL2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TrayNumLBL2, "#2");
    lv_obj_set_style_text_color(ui_TrayNumLBL2, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TrayNumLBL2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TrayLBL2 = lv_label_create(ui_TrayIMG2);
    lv_obj_set_width(ui_TrayLBL2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayLBL2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayLBL2, 29);
    lv_obj_set_y(ui_TrayLBL2, -1);
    lv_obj_set_align(ui_TrayLBL2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TrayLBL2, "Not Installed");
    lv_obj_set_style_text_color(ui_TrayLBL2, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TrayLBL2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TrayLBL2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TrayCheckIMG2 = lv_img_create(ui_TrayIMG2);
    lv_img_set_src(ui_TrayCheckIMG2, &ui_img_green_check_png);
    lv_obj_set_width(ui_TrayCheckIMG2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayCheckIMG2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayCheckIMG2, 40);
    lv_obj_set_y(ui_TrayCheckIMG2, 0);
    lv_obj_set_align(ui_TrayCheckIMG2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TrayCheckIMG2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TrayCheckIMG2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TrayIMG3 = lv_img_create(ui_PAGE1CON);
    lv_img_set_src(ui_TrayIMG3, &ui_img_tray_png);
    lv_obj_set_width(ui_TrayIMG3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayIMG3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayIMG3, 1);
    lv_obj_set_y(ui_TrayIMG3, -121);
    lv_obj_set_align(ui_TrayIMG3, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_TrayIMG3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TrayIMG3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_TrayIMG3, lv_color_hex(0x3175DD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TrayIMG3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_TrayIMG3, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_TrayIMG3, 152, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TrayIMG3, lv_color_hex(0x3175DD), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_TrayIMG3, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_width(ui_TrayIMG3, 3, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_pad(ui_TrayIMG3, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_TrayNumLBL3 = lv_label_create(ui_TrayIMG3);
    lv_obj_set_width(ui_TrayNumLBL3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayNumLBL3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayNumLBL3, 65);
    lv_obj_set_y(ui_TrayNumLBL3, -1);
    lv_obj_set_align(ui_TrayNumLBL3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TrayNumLBL3, "#3");
    lv_obj_set_style_text_color(ui_TrayNumLBL3, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TrayNumLBL3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TrayLBL3 = lv_label_create(ui_TrayIMG3);
    lv_obj_set_width(ui_TrayLBL3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayLBL3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayLBL3, 29);
    lv_obj_set_y(ui_TrayLBL3, -1);
    lv_obj_set_align(ui_TrayLBL3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TrayLBL3, "Not Installed");
    lv_obj_set_style_text_color(ui_TrayLBL3, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TrayLBL3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TrayLBL3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TrayCheckIMG3 = lv_img_create(ui_TrayIMG3);
    lv_img_set_src(ui_TrayCheckIMG3, &ui_img_green_check_png);
    lv_obj_set_width(ui_TrayCheckIMG3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayCheckIMG3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayCheckIMG3, 40);
    lv_obj_set_y(ui_TrayCheckIMG3, 0);
    lv_obj_set_align(ui_TrayCheckIMG3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TrayCheckIMG3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TrayCheckIMG3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TrayIMG4 = lv_img_create(ui_PAGE1CON);
    lv_img_set_src(ui_TrayIMG4, &ui_img_tray_png);
    lv_obj_set_width(ui_TrayIMG4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayIMG4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayIMG4, 1);
    lv_obj_set_y(ui_TrayIMG4, -153);
    lv_obj_set_align(ui_TrayIMG4, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_TrayIMG4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TrayIMG4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_TrayIMG4, lv_color_hex(0x3175DD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TrayIMG4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_TrayIMG4, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_TrayIMG4, 152, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TrayIMG4, lv_color_hex(0x3175DD), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_TrayIMG4, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_width(ui_TrayIMG4, 3, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_pad(ui_TrayIMG4, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_TrayNumLBL4 = lv_label_create(ui_TrayIMG4);
    lv_obj_set_width(ui_TrayNumLBL4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayNumLBL4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayNumLBL4, 65);
    lv_obj_set_y(ui_TrayNumLBL4, -1);
    lv_obj_set_align(ui_TrayNumLBL4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TrayNumLBL4, "#4");
    lv_obj_set_style_text_color(ui_TrayNumLBL4, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TrayNumLBL4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TrayLBL4 = lv_label_create(ui_TrayIMG4);
    lv_obj_set_width(ui_TrayLBL4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayLBL4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayLBL4, 29);
    lv_obj_set_y(ui_TrayLBL4, -1);
    lv_obj_set_align(ui_TrayLBL4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TrayLBL4, "Not Installed");
    lv_obj_set_style_text_color(ui_TrayLBL4, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TrayLBL4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TrayLBL4, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TrayCheckIMG4 = lv_img_create(ui_TrayIMG4);
    lv_img_set_src(ui_TrayCheckIMG4, &ui_img_green_check_png);
    lv_obj_set_width(ui_TrayCheckIMG4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayCheckIMG4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayCheckIMG4, 40);
    lv_obj_set_y(ui_TrayCheckIMG4, 0);
    lv_obj_set_align(ui_TrayCheckIMG4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TrayCheckIMG4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TrayCheckIMG4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TrayIMG5 = lv_img_create(ui_PAGE1CON);
    lv_img_set_src(ui_TrayIMG5, &ui_img_tray_png);
    lv_obj_set_width(ui_TrayIMG5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayIMG5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayIMG5, 1);
    lv_obj_set_y(ui_TrayIMG5, -185);
    lv_obj_set_align(ui_TrayIMG5, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_TrayIMG5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TrayIMG5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_TrayIMG5, lv_color_hex(0x3175DD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TrayIMG5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_TrayIMG5, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_TrayIMG5, 152, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TrayIMG5, lv_color_hex(0x3175DD), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_TrayIMG5, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_width(ui_TrayIMG5, 3, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_pad(ui_TrayIMG5, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_TrayNumLBL5 = lv_label_create(ui_TrayIMG5);
    lv_obj_set_width(ui_TrayNumLBL5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayNumLBL5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayNumLBL5, 65);
    lv_obj_set_y(ui_TrayNumLBL5, -1);
    lv_obj_set_align(ui_TrayNumLBL5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TrayNumLBL5, "#5");
    lv_obj_set_style_text_color(ui_TrayNumLBL5, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TrayNumLBL5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TrayLBL5 = lv_label_create(ui_TrayIMG5);
    lv_obj_set_width(ui_TrayLBL5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayLBL5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayLBL5, 29);
    lv_obj_set_y(ui_TrayLBL5, -1);
    lv_obj_set_align(ui_TrayLBL5, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TrayLBL5, "Not Installed");
    lv_obj_set_style_text_color(ui_TrayLBL5, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TrayLBL5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TrayLBL5, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TrayCheckIMG5 = lv_img_create(ui_TrayIMG5);
    lv_img_set_src(ui_TrayCheckIMG5, &ui_img_green_check_png);
    lv_obj_set_width(ui_TrayCheckIMG5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayCheckIMG5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayCheckIMG5, 40);
    lv_obj_set_y(ui_TrayCheckIMG5, 0);
    lv_obj_set_align(ui_TrayCheckIMG5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TrayCheckIMG5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TrayCheckIMG5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_UpIMGBTN = lv_imgbtn_create(ui_PAGE1CON);
    lv_imgbtn_set_src(ui_UpIMGBTN, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrowupdown_png, NULL);
    lv_imgbtn_set_src(ui_UpIMGBTN, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_arrowupdown_png, NULL);
    lv_obj_set_width(ui_UpIMGBTN, 110);
    lv_obj_set_height(ui_UpIMGBTN, 16);
    lv_obj_set_x(ui_UpIMGBTN, -29);
    lv_obj_set_y(ui_UpIMGBTN, -108);
    lv_obj_set_align(ui_UpIMGBTN, LV_ALIGN_CENTER);
    lv_obj_set_style_img_recolor(ui_UpIMGBTN, lv_color_hex(0x3175DE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_UpIMGBTN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PAGE2CON = lv_obj_create(ui_MainSCR);
    lv_obj_remove_style_all(ui_PAGE2CON);
    lv_obj_set_width(ui_PAGE2CON, 225);
    lv_obj_set_height(ui_PAGE2CON, 240);
    lv_obj_add_flag(ui_PAGE2CON, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PAGE2CON, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TopCapIMG = lv_img_create(ui_PAGE2CON);
    lv_img_set_src(ui_TopCapIMG, &ui_img_topcap_png);
    lv_obj_set_width(ui_TopCapIMG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TopCapIMG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TopCapIMG, 1);
    lv_obj_set_y(ui_TopCapIMG, -195);
    lv_obj_set_align(ui_TopCapIMG, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_TopCapIMG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TopCapIMG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DownIMGBTN = lv_imgbtn_create(ui_PAGE2CON);
    lv_imgbtn_set_src(ui_DownIMGBTN, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrowupdown2_png, NULL);
    lv_imgbtn_set_src(ui_DownIMGBTN, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_arrowupdown2_png, NULL);
    lv_obj_set_width(ui_DownIMGBTN, 110);
    lv_obj_set_height(ui_DownIMGBTN, 16);
    lv_obj_set_x(ui_DownIMGBTN, -29);
    lv_obj_set_y(ui_DownIMGBTN, 100);
    lv_obj_set_align(ui_DownIMGBTN, LV_ALIGN_CENTER);
    lv_obj_set_style_img_recolor(ui_DownIMGBTN, lv_color_hex(0x3175DE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_DownIMGBTN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TrayIMG6 = lv_img_create(ui_PAGE2CON);
    lv_img_set_src(ui_TrayIMG6, &ui_img_tray_png);
    lv_obj_set_width(ui_TrayIMG6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayIMG6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayIMG6, 1);
    lv_obj_set_y(ui_TrayIMG6, -35);
    lv_obj_set_align(ui_TrayIMG6, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_TrayIMG6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TrayIMG6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_TrayIMG6, lv_color_hex(0x3175DD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TrayIMG6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_TrayIMG6, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_TrayIMG6, 152, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TrayIMG6, lv_color_hex(0x3175DD), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_TrayIMG6, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_width(ui_TrayIMG6, 3, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_pad(ui_TrayIMG6, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_TrayNumLBL6 = lv_label_create(ui_TrayIMG6);
    lv_obj_set_width(ui_TrayNumLBL6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayNumLBL6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayNumLBL6, 65);
    lv_obj_set_y(ui_TrayNumLBL6, -1);
    lv_obj_set_align(ui_TrayNumLBL6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TrayNumLBL6, "#6");
    lv_obj_set_style_text_color(ui_TrayNumLBL6, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TrayNumLBL6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TrayLBL6 = lv_label_create(ui_TrayIMG6);
    lv_obj_set_width(ui_TrayLBL6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayLBL6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayLBL6, 29);
    lv_obj_set_y(ui_TrayLBL6, -1);
    lv_obj_set_align(ui_TrayLBL6, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TrayLBL6, "Not Installed");
    lv_obj_set_style_text_color(ui_TrayLBL6, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TrayLBL6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TrayLBL6, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TrayCheckIMG6 = lv_img_create(ui_TrayIMG6);
    lv_img_set_src(ui_TrayCheckIMG6, &ui_img_green_check_png);
    lv_obj_set_width(ui_TrayCheckIMG6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayCheckIMG6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayCheckIMG6, 40);
    lv_obj_set_y(ui_TrayCheckIMG6, 0);
    lv_obj_set_align(ui_TrayCheckIMG6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TrayCheckIMG6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TrayCheckIMG6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TrayIMG7 = lv_img_create(ui_PAGE2CON);
    lv_img_set_src(ui_TrayIMG7, &ui_img_tray_png);
    lv_obj_set_width(ui_TrayIMG7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayIMG7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayIMG7, 1);
    lv_obj_set_y(ui_TrayIMG7, -67);
    lv_obj_set_align(ui_TrayIMG7, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_TrayIMG7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TrayIMG7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_TrayIMG7, lv_color_hex(0x3175DD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TrayIMG7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_TrayIMG7, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_TrayIMG7, 152, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TrayIMG7, lv_color_hex(0x3175DD), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_TrayIMG7, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_width(ui_TrayIMG7, 3, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_pad(ui_TrayIMG7, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_TrayNumLBL7 = lv_label_create(ui_TrayIMG7);
    lv_obj_set_width(ui_TrayNumLBL7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayNumLBL7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayNumLBL7, 65);
    lv_obj_set_y(ui_TrayNumLBL7, -1);
    lv_obj_set_align(ui_TrayNumLBL7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TrayNumLBL7, "#7");
    lv_obj_set_style_text_color(ui_TrayNumLBL7, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TrayNumLBL7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TrayLBL7 = lv_label_create(ui_TrayIMG7);
    lv_obj_set_width(ui_TrayLBL7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayLBL7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayLBL7, 29);
    lv_obj_set_y(ui_TrayLBL7, -1);
    lv_obj_set_align(ui_TrayLBL7, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TrayLBL7, "Not Installed");
    lv_obj_set_style_text_color(ui_TrayLBL7, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TrayLBL7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TrayLBL7, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TrayCheckIMG7 = lv_img_create(ui_TrayIMG7);
    lv_img_set_src(ui_TrayCheckIMG7, &ui_img_green_check_png);
    lv_obj_set_width(ui_TrayCheckIMG7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayCheckIMG7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayCheckIMG7, 40);
    lv_obj_set_y(ui_TrayCheckIMG7, 0);
    lv_obj_set_align(ui_TrayCheckIMG7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TrayCheckIMG7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TrayCheckIMG7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TrayIMG8 = lv_img_create(ui_PAGE2CON);
    lv_img_set_src(ui_TrayIMG8, &ui_img_tray_png);
    lv_obj_set_width(ui_TrayIMG8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayIMG8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayIMG8, 1);
    lv_obj_set_y(ui_TrayIMG8, -99);
    lv_obj_set_align(ui_TrayIMG8, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_TrayIMG8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TrayIMG8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_TrayIMG8, lv_color_hex(0x3175DD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TrayIMG8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_TrayIMG8, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_TrayIMG8, 152, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TrayIMG8, lv_color_hex(0x3175DD), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_TrayIMG8, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_width(ui_TrayIMG8, 3, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_pad(ui_TrayIMG8, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_TrayNumLBL8 = lv_label_create(ui_TrayIMG8);
    lv_obj_set_width(ui_TrayNumLBL8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayNumLBL8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayNumLBL8, 65);
    lv_obj_set_y(ui_TrayNumLBL8, -1);
    lv_obj_set_align(ui_TrayNumLBL8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TrayNumLBL8, "#8");
    lv_obj_set_style_text_color(ui_TrayNumLBL8, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TrayNumLBL8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TrayLBL8 = lv_label_create(ui_TrayIMG8);
    lv_obj_set_width(ui_TrayLBL8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayLBL8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayLBL8, 29);
    lv_obj_set_y(ui_TrayLBL8, -1);
    lv_obj_set_align(ui_TrayLBL8, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TrayLBL8, "Not Installed");
    lv_obj_set_style_text_color(ui_TrayLBL8, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TrayLBL8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TrayLBL8, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TrayCheckIMG8 = lv_img_create(ui_TrayIMG8);
    lv_img_set_src(ui_TrayCheckIMG8, &ui_img_green_check_png);
    lv_obj_set_width(ui_TrayCheckIMG8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayCheckIMG8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayCheckIMG8, 40);
    lv_obj_set_y(ui_TrayCheckIMG8, 0);
    lv_obj_set_align(ui_TrayCheckIMG8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TrayCheckIMG8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TrayCheckIMG8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TrayIMG9 = lv_img_create(ui_PAGE2CON);
    lv_img_set_src(ui_TrayIMG9, &ui_img_tray_png);
    lv_obj_set_width(ui_TrayIMG9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayIMG9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayIMG9, 1);
    lv_obj_set_y(ui_TrayIMG9, -131);
    lv_obj_set_align(ui_TrayIMG9, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_TrayIMG9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TrayIMG9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_TrayIMG9, lv_color_hex(0x3175DD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TrayIMG9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_TrayIMG9, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_TrayIMG9, 152, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TrayIMG9, lv_color_hex(0x3175DD), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_TrayIMG9, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_width(ui_TrayIMG9, 3, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_pad(ui_TrayIMG9, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_TrayNumLBL9 = lv_label_create(ui_TrayIMG9);
    lv_obj_set_width(ui_TrayNumLBL9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayNumLBL9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayNumLBL9, 65);
    lv_obj_set_y(ui_TrayNumLBL9, -1);
    lv_obj_set_align(ui_TrayNumLBL9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TrayNumLBL9, "#9");
    lv_obj_set_style_text_color(ui_TrayNumLBL9, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TrayNumLBL9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TrayLBL9 = lv_label_create(ui_TrayIMG9);
    lv_obj_set_width(ui_TrayLBL9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayLBL9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayLBL9, 29);
    lv_obj_set_y(ui_TrayLBL9, -1);
    lv_obj_set_align(ui_TrayLBL9, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TrayLBL9, "Not Installed");
    lv_obj_set_style_text_color(ui_TrayLBL9, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TrayLBL9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TrayLBL9, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TrayCheckIMG9 = lv_img_create(ui_TrayIMG9);
    lv_img_set_src(ui_TrayCheckIMG9, &ui_img_green_check_png);
    lv_obj_set_width(ui_TrayCheckIMG9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayCheckIMG9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayCheckIMG9, 40);
    lv_obj_set_y(ui_TrayCheckIMG9, 0);
    lv_obj_set_align(ui_TrayCheckIMG9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TrayCheckIMG9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TrayCheckIMG9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TrayIMG10 = lv_img_create(ui_PAGE2CON);
    lv_img_set_src(ui_TrayIMG10, &ui_img_tray_png);
    lv_obj_set_width(ui_TrayIMG10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayIMG10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayIMG10, 1);
    lv_obj_set_y(ui_TrayIMG10, -163);
    lv_obj_set_align(ui_TrayIMG10, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_TrayIMG10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TrayIMG10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_TrayIMG10, lv_color_hex(0x3175DD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TrayIMG10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_TrayIMG10, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_TrayIMG10, 152, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TrayIMG10, lv_color_hex(0x3175DD), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_TrayIMG10, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_width(ui_TrayIMG10, 3, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_pad(ui_TrayIMG10, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_TrayNumLBL10 = lv_label_create(ui_TrayIMG10);
    lv_obj_set_width(ui_TrayNumLBL10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayNumLBL10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayNumLBL10, 65);
    lv_obj_set_y(ui_TrayNumLBL10, -1);
    lv_obj_set_align(ui_TrayNumLBL10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TrayNumLBL10, "#10");
    lv_obj_set_style_text_color(ui_TrayNumLBL10, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TrayNumLBL10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TrayLBL10 = lv_label_create(ui_TrayIMG10);
    lv_obj_set_width(ui_TrayLBL10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayLBL10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayLBL10, 29);
    lv_obj_set_y(ui_TrayLBL10, -1);
    lv_obj_set_align(ui_TrayLBL10, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TrayLBL10, "Not Installed");
    lv_obj_set_style_text_color(ui_TrayLBL10, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TrayLBL10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TrayLBL10, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TrayCheckIMG10 = lv_img_create(ui_TrayIMG10);
    lv_img_set_src(ui_TrayCheckIMG10, &ui_img_green_check_png);
    lv_obj_set_width(ui_TrayCheckIMG10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrayCheckIMG10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrayCheckIMG10, 40);
    lv_obj_set_y(ui_TrayCheckIMG10, 0);
    lv_obj_set_align(ui_TrayCheckIMG10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TrayCheckIMG10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TrayCheckIMG10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DismissBTN = lv_btn_create(ui_MainSCR);
    lv_obj_set_width(ui_DismissBTN, 78);
    lv_obj_set_height(ui_DismissBTN, 88);
    lv_obj_set_x(ui_DismissBTN, 112);
    lv_obj_set_y(ui_DismissBTN, 70);
    lv_obj_set_align(ui_DismissBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DismissBTN, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DismissBTN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DismissBTN, lv_color_hex(0x941818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DismissBTN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DismissBTN, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DissmissBTNLBL = lv_label_create(ui_DismissBTN);
    lv_obj_set_width(ui_DissmissBTNLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DissmissBTNLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DissmissBTNLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DissmissBTNLBL, "Dismiss\nAlert\nOnly");
    lv_obj_set_style_text_align(ui_DissmissBTNLBL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DissmissBTNLBL, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DismissPAN = lv_obj_create(ui_MainSCR);
    lv_obj_set_width(ui_DismissPAN, 319);
    lv_obj_set_height(ui_DismissPAN, 239);
    lv_obj_set_align(ui_DismissPAN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DismissPAN, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_DismissPAN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TrueDismissBTN = lv_btn_create(ui_DismissPAN);
    lv_obj_set_width(ui_TrueDismissBTN, 150);
    lv_obj_set_height(ui_TrueDismissBTN, 88);
    lv_obj_set_x(ui_TrueDismissBTN, 78);
    lv_obj_set_y(ui_TrueDismissBTN, 70);
    lv_obj_set_align(ui_TrueDismissBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TrueDismissBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TrueDismissBTN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TrueDismissBTN, lv_color_hex(0x3175DE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TrueDismissBTN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TrueDissmissBTNLBL = lv_label_create(ui_TrueDismissBTN);
    lv_obj_set_width(ui_TrueDissmissBTNLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrueDissmissBTNLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TrueDissmissBTNLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TrueDissmissBTNLBL, "DISMISS\nPILLS");
    lv_obj_set_style_text_align(ui_TrueDissmissBTNLBL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TrueDissmissBTNLBL, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DismissCancelBTN = lv_btn_create(ui_DismissPAN);
    lv_obj_set_width(ui_DismissCancelBTN, 150);
    lv_obj_set_height(ui_DismissCancelBTN, 88);
    lv_obj_set_x(ui_DismissCancelBTN, -78);
    lv_obj_set_y(ui_DismissCancelBTN, 70);
    lv_obj_set_align(ui_DismissCancelBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DismissCancelBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DismissCancelBTN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DismissCancelBTN, lv_color_hex(0x941818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DismissCancelBTN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DismissCancelBTNLBL = lv_label_create(ui_DismissCancelBTN);
    lv_obj_set_width(ui_DismissCancelBTNLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DismissCancelBTNLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DismissCancelBTNLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DismissCancelBTNLBL, "CANCEL");
    lv_obj_set_style_text_align(ui_DismissCancelBTNLBL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DismissCancelBTNLBL, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DismissLBL = lv_label_create(ui_DismissPAN);
    lv_obj_set_width(ui_DismissLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DismissLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DismissLBL, 0);
    lv_obj_set_y(ui_DismissLBL, -50);
    lv_obj_set_align(ui_DismissLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DismissLBL, "Are you sure you want \nto dismiss thoses \npills for today ?");
    lv_obj_set_style_text_align(ui_DismissLBL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DismissLBL, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DismissLBL, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DismissLBL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DoubletakePAN = lv_obj_create(ui_MainSCR);
    lv_obj_set_width(ui_DoubletakePAN, 319);
    lv_obj_set_height(ui_DoubletakePAN, 239);
    lv_obj_set_align(ui_DoubletakePAN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DoubletakePAN, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_DoubletakePAN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DispenseAgainBTN = lv_btn_create(ui_DoubletakePAN);
    lv_obj_set_width(ui_DispenseAgainBTN, 150);
    lv_obj_set_height(ui_DispenseAgainBTN, 88);
    lv_obj_set_x(ui_DispenseAgainBTN, 78);
    lv_obj_set_y(ui_DispenseAgainBTN, 70);
    lv_obj_set_align(ui_DispenseAgainBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DispenseAgainBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DispenseAgainBTN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DispenseAgainBTN, lv_color_hex(0x3175DE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DispenseAgainBTN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DispenseAgainBTNLBL = lv_label_create(ui_DispenseAgainBTN);
    lv_obj_set_width(ui_DispenseAgainBTNLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DispenseAgainBTNLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DispenseAgainBTNLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DispenseAgainBTNLBL, "DISPENSE\nPILLS\nAGAIN");
    lv_obj_set_style_text_align(ui_DispenseAgainBTNLBL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DispenseAgainBTNLBL, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DoubleDispenseCancelBTN = lv_btn_create(ui_DoubletakePAN);
    lv_obj_set_width(ui_DoubleDispenseCancelBTN, 150);
    lv_obj_set_height(ui_DoubleDispenseCancelBTN, 88);
    lv_obj_set_x(ui_DoubleDispenseCancelBTN, -78);
    lv_obj_set_y(ui_DoubleDispenseCancelBTN, 70);
    lv_obj_set_align(ui_DoubleDispenseCancelBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DoubleDispenseCancelBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DoubleDispenseCancelBTN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DoubleDispenseCancelBTN, lv_color_hex(0x941818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DoubleDispenseCancelBTN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DoubleDispenseCancelBTNLBL = lv_label_create(ui_DoubleDispenseCancelBTN);
    lv_obj_set_width(ui_DoubleDispenseCancelBTNLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DoubleDispenseCancelBTNLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DoubleDispenseCancelBTNLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DoubleDispenseCancelBTNLBL, "CANCEL");
    lv_obj_set_style_text_align(ui_DoubleDispenseCancelBTNLBL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DoubleDispenseCancelBTNLBL, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DoubleDispenseLBL = lv_label_create(ui_DoubletakePAN);
    lv_obj_set_width(ui_DoubleDispenseLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DoubleDispenseLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DoubleDispenseLBL, 0);
    lv_obj_set_y(ui_DoubleDispenseLBL, -50);
    lv_obj_set_align(ui_DoubleDispenseLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DoubleDispenseLBL,
                      "Thoses pills already have been\ndispensed for the day, \nare you sure you want to \ndispense them again ?");
    lv_obj_set_style_text_align(ui_DoubleDispenseLBL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DoubleDispenseLBL, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DoubleDispenseLBL, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DoubleDispenseLBL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SettingBTN, ui_event_SettingBTN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TraycfgBTN, ui_event_TraycfgBTN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_UpIMGBTN, ui_event_UpIMGBTN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DownIMGBTN, ui_event_DownIMGBTN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DismissBTN, ui_event_DismissBTN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TrueDismissBTN, ui_event_TrueDismissBTN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DismissCancelBTN, ui_event_DismissCancelBTN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DispenseAgainBTN, ui_event_DispenseAgainBTN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DoubleDispenseCancelBTN, ui_event_DoubleDispenseCancelBTN, LV_EVENT_ALL, NULL);

}
