// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_PickPillsSCR_screen_init(void)
{
    ui_PickPillsSCR = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PickPillsSCR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PickPillsSCR, lv_color_hex(0xD5E6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PickPillsSCR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TakepillsIMG = lv_img_create(ui_PickPillsSCR);
    lv_img_set_src(ui_TakepillsIMG, &ui_img_apd_takepills_png);
    lv_obj_set_width(ui_TakepillsIMG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TakepillsIMG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TakepillsIMG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TakepillsIMG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TakepillsIMG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_PickPillsSCR, ui_event_PickPillsSCR, LV_EVENT_ALL, NULL);

}
