// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_SettingSCR_screen_init(void)
{
    ui_SettingSCR = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingSCR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingSCR, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingSCR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiBTN = lv_btn_create(ui_SettingSCR);
    lv_obj_set_width(ui_WifiBTN, 122);
    lv_obj_set_height(ui_WifiBTN, 24);
    lv_obj_set_x(ui_WifiBTN, 11);
    lv_obj_set_y(ui_WifiBTN, 3);
    lv_obj_clear_flag(ui_WifiBTN, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_WifiBTN, lv_color_hex(0x3175DD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiBTN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiBTNLBL = lv_label_create(ui_WifiBTN);
    lv_obj_set_width(ui_WifiBTNLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiBTNLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiBTNLBL, 0);
    lv_obj_set_y(ui_WifiBTNLBL, 1);
    lv_obj_set_align(ui_WifiBTNLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiBTNLBL, "Wifi Network");

    ui_WifiClearBTN = lv_btn_create(ui_SettingSCR);
    lv_obj_set_width(ui_WifiClearBTN, 122);
    lv_obj_set_height(ui_WifiClearBTN, 24);
    lv_obj_set_x(ui_WifiClearBTN, 11);
    lv_obj_set_y(ui_WifiClearBTN, 34);
    lv_obj_clear_flag(ui_WifiClearBTN, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_WifiClearBTN, lv_color_hex(0x941818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiClearBTN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiClearBTNLBL = lv_label_create(ui_WifiClearBTN);
    lv_obj_set_width(ui_WifiClearBTNLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiClearBTNLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiClearBTNLBL, 0);
    lv_obj_set_y(ui_WifiClearBTNLBL, 1);
    lv_obj_set_align(ui_WifiClearBTNLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiClearBTNLBL, "Wifi Clear");

    ui_UTCSlider = lv_slider_create(ui_SettingSCR);
    lv_slider_set_range(ui_UTCSlider, -12, 12);
    lv_slider_set_mode(ui_UTCSlider, LV_SLIDER_MODE_SYMMETRICAL);
    lv_slider_set_value(ui_UTCSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_UTCSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_UTCSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_UTCSlider, 160);
    lv_obj_set_height(ui_UTCSlider, 10);
    lv_obj_set_x(ui_UTCSlider, 135);
    lv_obj_set_y(ui_UTCSlider, 213);
    lv_obj_set_style_bg_color(ui_UTCSlider, lv_color_hex(0x3175DE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UTCSlider, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_UTCSlider, lv_color_hex(0x294473), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UTCSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_UTCSlider, lv_color_hex(0x3175DE), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UTCSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_VolSlider = lv_slider_create(ui_SettingSCR);
    lv_slider_set_range(ui_VolSlider, 1, 30);
    lv_slider_set_value(ui_VolSlider, 1, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_VolSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_VolSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_VolSlider, 113);
    lv_obj_set_height(ui_VolSlider, 10);
    lv_obj_set_x(ui_VolSlider, 135);
    lv_obj_set_y(ui_VolSlider, 157);
    lv_obj_set_style_bg_color(ui_VolSlider, lv_color_hex(0x3175DE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VolSlider, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_VolSlider, lv_color_hex(0x294473), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VolSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_VolSlider, lv_color_hex(0x3175DE), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VolSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_UTCLBL = lv_label_create(ui_SettingSCR);
    lv_obj_set_width(ui_UTCLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UTCLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UTCLBL, 15);
    lv_obj_set_y(ui_UTCLBL, 210);
    lv_label_set_text(ui_UTCLBL, "UTC Offset: 0");
    lv_obj_set_style_text_align(ui_UTCLBL, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VolLBL = lv_label_create(ui_SettingSCR);
    lv_obj_set_width(ui_VolLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VolLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VolLBL, 15);
    lv_obj_set_y(ui_VolLBL, 154);
    lv_label_set_text(ui_VolLBL, "Volume:");
    lv_obj_set_style_text_align(ui_VolLBL, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MuteCHK = lv_checkbox_create(ui_SettingSCR);
    lv_checkbox_set_text(ui_MuteCHK, "Mute sounds");
    lv_obj_set_width(ui_MuteCHK, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MuteCHK, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MuteCHK, 15);
    lv_obj_set_y(ui_MuteCHK, 123);
    lv_obj_add_flag(ui_MuteCHK, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_border_color(ui_MuteCHK, lv_color_hex(0x3175DE), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MuteCHK, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MuteCHK, lv_color_hex(0x3175DE), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_MuteCHK, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_DSTCHK = lv_checkbox_create(ui_SettingSCR);
    lv_checkbox_set_text(ui_DSTCHK, "DST");
    lv_obj_set_width(ui_DSTCHK, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DSTCHK, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DSTCHK, 15);
    lv_obj_set_y(ui_DSTCHK, 181);
    lv_obj_add_flag(ui_DSTCHK, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_border_color(ui_DSTCHK, lv_color_hex(0x3175DE), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DSTCHK, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DSTCHK, lv_color_hex(0x3175DE), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_DSTCHK, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_SettingBackBTN = lv_btn_create(ui_SettingSCR);
    lv_obj_set_width(ui_SettingBackBTN, 128);
    lv_obj_set_height(ui_SettingBackBTN, 24);
    lv_obj_set_x(ui_SettingBackBTN, 180);
    lv_obj_set_y(ui_SettingBackBTN, 3);
    lv_obj_clear_flag(ui_SettingBackBTN,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_SettingBackBTN, lv_color_hex(0x3175DD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingBackBTN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingBackBTNLBL = lv_label_create(ui_SettingBackBTN);
    lv_obj_set_width(ui_SettingBackBTNLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingBackBTNLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingBackBTNLBL, 0);
    lv_obj_set_y(ui_SettingBackBTNLBL, 1);
    lv_obj_set_align(ui_SettingBackBTNLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingBackBTNLBL, "Save & Restart");

    ui_HowManyTrayDROP = lv_dropdown_create(ui_SettingSCR);
    lv_dropdown_set_options(ui_HowManyTrayDROP, "1\n2\n3\n4\n5\n6\n7\n8\n9\n10");
    lv_obj_set_width(ui_HowManyTrayDROP, 68);
    lv_obj_set_height(ui_HowManyTrayDROP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HowManyTrayDROP, -112);
    lv_obj_set_y(ui_HowManyTrayDROP, -26);
    lv_obj_set_align(ui_HowManyTrayDROP, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HowManyTrayDROP, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_border_color(ui_HowManyTrayDROP, lv_color_hex(0x3175DE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HowManyTrayDROP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_InstalledTrayLBL = lv_label_create(ui_SettingSCR);
    lv_obj_set_width(ui_InstalledTrayLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_InstalledTrayLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_InstalledTrayLBL, -38);
    lv_obj_set_y(ui_InstalledTrayLBL, -26);
    lv_obj_set_align(ui_InstalledTrayLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_InstalledTrayLBL, "Trays\ninstalled");

    ui_ScreensaverCHK1 = lv_checkbox_create(ui_SettingSCR);
    lv_checkbox_set_text(ui_ScreensaverCHK1, "Time/Date as Screensaver");
    lv_obj_set_width(ui_ScreensaverCHK1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScreensaverCHK1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScreensaverCHK1, 90);
    lv_obj_set_y(ui_ScreensaverCHK1, 181);
    lv_obj_add_flag(ui_ScreensaverCHK1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_border_color(ui_ScreensaverCHK1, lv_color_hex(0x3175DE), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ScreensaverCHK1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreensaverCHK1, lv_color_hex(0x3175DE), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ScreensaverCHK1, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_SettingBackBTN1 = lv_btn_create(ui_SettingSCR);
    lv_obj_set_width(ui_SettingBackBTN1, 128);
    lv_obj_set_height(ui_SettingBackBTN1, 24);
    lv_obj_set_x(ui_SettingBackBTN1, 180);
    lv_obj_set_y(ui_SettingBackBTN1, 34);
    lv_obj_clear_flag(ui_SettingBackBTN1,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_SettingBackBTN1, lv_color_hex(0x941818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingBackBTN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingBackBTNLBL1 = lv_label_create(ui_SettingBackBTN1);
    lv_obj_set_width(ui_SettingBackBTNLBL1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingBackBTNLBL1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingBackBTNLBL1, 0);
    lv_obj_set_y(ui_SettingBackBTNLBL1, 1);
    lv_obj_set_align(ui_SettingBackBTNLBL1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingBackBTNLBL1, "Cancel");

    ui_VolTestBTN = lv_btn_create(ui_SettingSCR);
    lv_obj_set_width(ui_VolTestBTN, 38);
    lv_obj_set_height(ui_VolTestBTN, 24);
    lv_obj_set_x(ui_VolTestBTN, 257);
    lv_obj_set_y(ui_VolTestBTN, 150);
    lv_obj_clear_flag(ui_VolTestBTN, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_VolTestBTN, lv_color_hex(0x3175DD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VolTestBTN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VolTestBTNLBL = lv_label_create(ui_VolTestBTN);
    lv_obj_set_width(ui_VolTestBTNLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VolTestBTNLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VolTestBTNLBL, 0);
    lv_obj_set_y(ui_VolTestBTNLBL, 1);
    lv_obj_set_align(ui_VolTestBTNLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VolTestBTNLBL, "Test");

    ui_DayHourDROP = lv_dropdown_create(ui_SettingSCR);
    lv_dropdown_set_options(ui_DayHourDROP,
                            "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23");
    lv_obj_set_width(ui_DayHourDROP, 60);
    lv_obj_set_height(ui_DayHourDROP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DayHourDROP, 172);
    lv_obj_set_y(ui_DayHourDROP, 94);
    lv_obj_add_flag(ui_DayHourDROP, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_border_color(ui_DayHourDROP, lv_color_hex(0x3175DE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DayHourDROP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_DayMinutesDROP = lv_dropdown_create(ui_SettingSCR);
    lv_dropdown_set_options(ui_DayMinutesDROP, "00\n05\n10\n15\n20\n25\n30\n35\n40\n45\n50\n55\n");
    lv_obj_set_width(ui_DayMinutesDROP, 60);
    lv_obj_set_height(ui_DayMinutesDROP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DayMinutesDROP, 235);
    lv_obj_set_y(ui_DayMinutesDROP, 93);
    lv_obj_add_flag(ui_DayMinutesDROP, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_border_color(ui_DayMinutesDROP, lv_color_hex(0x3175DE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DayMinutesDROP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_StartofthedayLBL = lv_label_create(ui_SettingSCR);
    lv_obj_set_width(ui_StartofthedayLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StartofthedayLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StartofthedayLBL, 74);
    lv_obj_set_y(ui_StartofthedayLBL, -39);
    lv_obj_set_align(ui_StartofthedayLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StartofthedayLBL, "Start of the Day");

    ui_WifiInfoLBL = lv_label_create(ui_SettingSCR);
    lv_obj_set_width(ui_WifiInfoLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiInfoLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiInfoLBL, 74);
    lv_obj_set_y(ui_WifiInfoLBL, -16);
    lv_obj_set_align(ui_WifiInfoLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiInfoLBL,
                      "Without wifi connection \nyou cannot set time \nand you will have \nno automatic alerts.");
    lv_obj_set_style_text_align(ui_WifiInfoLBL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WifiInfoLBL, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WifiInfoLBL, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiInfoLBL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_WifiBTN, ui_event_WifiBTN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_UTCSlider, ui_event_UTCSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingBackBTN1, ui_event_SettingBackBTN1, LV_EVENT_ALL, NULL);

}
