// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_SplashSCR_screen_init(void)
{
    ui_SplashSCR = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SplashSCR, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_style_bg_color(ui_SplashSCR, lv_color_hex(0xD7E6F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SplashSCR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LoadingBAR = lv_bar_create(ui_SplashSCR);
    lv_bar_set_range(ui_LoadingBAR, 0, 14);
    lv_bar_set_value(ui_LoadingBAR, 1, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_LoadingBAR, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_LoadingBAR, 270);
    lv_obj_set_height(ui_LoadingBAR, 18);
    lv_obj_set_x(ui_LoadingBAR, 0);
    lv_obj_set_y(ui_LoadingBAR, 80);
    lv_obj_set_align(ui_LoadingBAR, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_LoadingBAR, lv_color_hex(0x3175DD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LoadingBAR, 80, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_LoadingBAR, lv_color_hex(0x3175DD), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LoadingBAR, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LoadinginfoLBL = lv_label_create(ui_SplashSCR);
    lv_obj_set_width(ui_LoadinginfoLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LoadinginfoLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LoadinginfoLBL, 0);
    lv_obj_set_y(ui_LoadinginfoLBL, 104);
    lv_obj_set_align(ui_LoadinginfoLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LoadinginfoLBL, "Loading interface...");
    lv_obj_set_style_text_color(ui_LoadinginfoLBL, lv_color_hex(0x18204A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LoadinginfoLBL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VersionLBL = lv_label_create(ui_SplashSCR);
    lv_obj_set_width(ui_VersionLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VersionLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VersionLBL, 0);
    lv_obj_set_y(ui_VersionLBL, 58);
    lv_obj_set_align(ui_VersionLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VersionLBL, "v.1.0");
    lv_obj_set_style_text_color(ui_VersionLBL, lv_color_hex(0x18204A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VersionLBL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VersionLBL, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogoIMG = lv_img_create(ui_SplashSCR);
    lv_img_set_src(ui_LogoIMG, &ui_img_apdlogo_png);
    lv_obj_set_width(ui_LogoIMG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LogoIMG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LogoIMG, 0);
    lv_obj_set_y(ui_LogoIMG, -34);
    lv_obj_set_align(ui_LogoIMG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LogoIMG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LogoIMG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
