// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Setting2SCR_screen_init(void)
{
    ui_Setting2SCR = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Setting2SCR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Setting2SCR, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Setting2SCR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


}
