// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_WifiSCR_screen_init(void)
{
    ui_WifiSCR = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WifiSCR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiSCR, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiSCR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SSIDDropDown = lv_dropdown_create(ui_WifiSCR);
    lv_dropdown_set_options(ui_SSIDDropDown, "");
    lv_obj_set_width(ui_SSIDDropDown, 262);
    lv_obj_set_height(ui_SSIDDropDown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SSIDDropDown, 21);
    lv_obj_set_y(ui_SSIDDropDown, -68);
    lv_obj_set_align(ui_SSIDDropDown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SSIDDropDown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_bg_color(ui_SSIDDropDown, lv_color_hex(0x293031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SSIDDropDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SSIDDropDown, lv_color_hex(0x3175DE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SSIDDropDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Keyboard = lv_keyboard_create(ui_WifiSCR);
    lv_obj_set_width(ui_Keyboard, 320);
    lv_obj_set_height(ui_Keyboard, 120);
    lv_obj_set_align(ui_Keyboard, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_bg_color(ui_Keyboard, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Keyboard, lv_color_hex(0x3175DE), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_PassTxtBox = lv_textarea_create(ui_WifiSCR);
    lv_obj_set_width(ui_PassTxtBox, 262);
    lv_obj_set_height(ui_PassTxtBox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PassTxtBox, 50);
    lv_obj_set_y(ui_PassTxtBox, 75);
    lv_textarea_set_max_length(ui_PassTxtBox, 32);
    lv_textarea_set_one_line(ui_PassTxtBox, true);
    lv_textarea_set_password_mode(ui_PassTxtBox, true);
    lv_obj_set_style_bg_color(ui_PassTxtBox, lv_color_hex(0x293031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PassTxtBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PassTxtBox, lv_color_hex(0x3175DE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PassTxtBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_SSIDLBL = lv_label_create(ui_WifiSCR);
    lv_obj_set_width(ui_SSIDLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SSIDLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SSIDLBL, -135);
    lv_obj_set_y(ui_SSIDLBL, -69);
    lv_obj_set_align(ui_SSIDLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SSIDLBL, "SSID:");
    lv_obj_clear_flag(ui_SSIDLBL, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_PassLBL = lv_label_create(ui_WifiSCR);
    lv_obj_set_width(ui_PassLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PassLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PassLBL, -136);
    lv_obj_set_y(ui_PassLBL, -26);
    lv_obj_set_align(ui_PassLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PassLBL, "Pass:");
    lv_obj_clear_flag(ui_PassLBL, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_WIFILBL = lv_label_create(ui_WifiSCR);
    lv_obj_set_width(ui_WIFILBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WIFILBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WIFILBL, 0);
    lv_obj_set_y(ui_WIFILBL, -107);
    lv_obj_set_align(ui_WIFILBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WIFILBL, "Wifi Connection");
    lv_obj_clear_flag(ui_WIFILBL, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_decor(ui_WIFILBL, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SkipWifiBTN = lv_btn_create(ui_WifiSCR);
    lv_obj_set_width(ui_SkipWifiBTN, 68);
    lv_obj_set_height(ui_SkipWifiBTN, 21);
    lv_obj_set_x(ui_SkipWifiBTN, 247);
    lv_obj_set_y(ui_SkipWifiBTN, 2);
    lv_obj_clear_flag(ui_SkipWifiBTN, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_SkipWifiBTN, lv_color_hex(0x3175DD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SkipWifiBTN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SkipWifiBTNLBL = lv_label_create(ui_SkipWifiBTN);
    lv_obj_set_width(ui_SkipWifiBTNLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SkipWifiBTNLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SkipWifiBTNLBL, 0);
    lv_obj_set_y(ui_SkipWifiBTNLBL, 1);
    lv_obj_set_align(ui_SkipWifiBTNLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SkipWifiBTNLBL, "Cancel");

    ui_ScanWifiBTN = lv_btn_create(ui_WifiSCR);
    lv_obj_set_width(ui_ScanWifiBTN, 68);
    lv_obj_set_height(ui_ScanWifiBTN, 21);
    lv_obj_set_x(ui_ScanWifiBTN, 3);
    lv_obj_set_y(ui_ScanWifiBTN, 2);
    lv_obj_clear_flag(ui_ScanWifiBTN, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_ScanWifiBTN, lv_color_hex(0x3175DD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScanWifiBTN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScanWifiBTNLBL = lv_label_create(ui_ScanWifiBTN);
    lv_obj_set_width(ui_ScanWifiBTNLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScanWifiBTNLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScanWifiBTNLBL, 0);
    lv_obj_set_y(ui_ScanWifiBTNLBL, 1);
    lv_obj_set_align(ui_ScanWifiBTNLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScanWifiBTNLBL, "Scan");

    ui_WifiScanPAN = lv_obj_create(ui_WifiSCR);
    lv_obj_set_width(ui_WifiScanPAN, 320);
    lv_obj_set_height(ui_WifiScanPAN, 207);
    lv_obj_set_x(ui_WifiScanPAN, 0);
    lv_obj_set_y(ui_WifiScanPAN, 14);
    lv_obj_set_align(ui_WifiScanPAN, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WifiScanPAN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiScanPANLBL = lv_label_create(ui_WifiScanPAN);
    lv_obj_set_width(ui_WifiScanPANLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiScanPANLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiScanPANLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiScanPANLBL, "Please wait...\n\nScanning wifi networks \nin progress");
    lv_obj_set_style_text_align(ui_WifiScanPANLBL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WifiScanPANLBL, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_keyboard_set_textarea(ui_Keyboard, ui_PassTxtBox);
    lv_obj_add_event_cb(ui_SkipWifiBTN, ui_event_SkipWifiBTN, LV_EVENT_ALL, NULL);

}
